### PR TITLE
implement buf workflow

### LINKED ISSUE #1: Implement Buf Build Workflow
Implement a buf BSR workflow with https://buf.build

https://buf.build/scoretrak/scoretrakapis

### PR DESCRIPTION
**Pull request by thisisibrahimd**
Please note that this will break if you update in the other repos.

### CODE REVIEW

**Comment by L1ghtman2k** [comment]
do you recall why i waited on this one? i can't remember why we didn't push it a while ago

**Comment by thisisibrahimd** [comment]
> do you recall why i waited on this one? i can't remember why we didn't push it a while ago

I believe we were trying to figure out out to grab generated proto files from this repo into the server and client.
https://docs.buf.build/generate/usage#common-use-cases

**Comment by thisisibrahimd** [comment]
Go should be fine but after talking with people in the buf build slack, it is better to use the link above and call the buf generated with this repo url. 
https://bufbuild.slack.com/archives/CRZ680FUH/p1637100789250600

**Comment by L1ghtman2k** [comment]
okay, lets get it working once cobra merged

**Comment by thisisibrahimd** [comment]
Added documentation on how to retrieve go generated grpc code and other languages such as typescript by executing buf generate with the github repository url

**Comment by L1ghtman2k** [comment]
Let's merge this here, and test it on PRs at /client, and /scoretrak repos
Overall, looks great!

**Pull request merged**
