### PR TITLE
Feat fix naming convetion

### PR DESCRIPTION
**Pull request by thisisibrahimd**

### CODE REVIEW

**Comment by thisisibrahimd** [comment]
Proposal of a format for object from the scoretrak server. However, other functions can exist like get user by username or specialized functions like load_competition etc...
```
Get<plural_message>
	limit
	offset
	
	Message[]

Get<singular_message>
	ID

	Message

Create<plural_message>
	Message[]

	ids[]

Create<singular_message>
	Message
	
	id

Update<singular_message>
	Message

	void

Delete<singular_message>
	id

	void

```

Reason for this: I don't like suggested format from buf which is UserServiceGetByIDRequest.

Let me know your thoughts and if I should what I suggested or buf recommended format.

**Comment by L1ghtman2k** [comment]
I like this naming standardization, let's get this merged and tested

**Comment by thisisibrahimd** [comment]
I haven't made changes for the proposed format. The current commit in this pr are for the buf recommended format.

> I like this naming standardization, let's get this merged and tested

Which one? The buf format? @L1ghtman2k 

May have prematurely requested a review. Should have @'d.

**Comment by L1ghtman2k** [comment]
> I haven't made changes for the proposed format. The current commit in this pr are for the buf recommended format.
> 
> > I like this naming standardization, let's get this merged and tested
> 
> Which one? The buf format? @L1ghtman2k 

This one was in regard to the format you mentioned in the message ~4 hours ago :D

**Comment by thisisibrahimd** [comment]
> > I haven't made changes for the proposed format. The current commit in this pr are for the buf recommended format.
> > > I like this naming standardization, let's get this merged and tested
> > 
> > 
> > Which one? The buf format? @L1ghtman2k
> 
> This one was in regard to the format you mentioned in the message ~4 hours ago :D

👍. Then I need to revert this merge the commits in this pr contain changes to buf recommended format.

**Pull request merged**
